### ISSUE TITLE
Why not use this methond to finetune Bert?

### ISSUE THREAD

**Issue by hlang8160** [BinWang28/SBERT-WK-Sentence-Embedding#6]
Hi~
I am a beginner, I have a question.
Why not use this method to obtain wk-sentence-embedding and then based on sentence-bert model fintune NLI data to get finetuned model?  I see you only based on pre-train model to obtain wk-sentence-embedding to evaluate result. Thank you very much.

**Comment by BinWang28** [comment]
Hi @hlang8160,
Good point. The method you have mentioned may help. You're more than welcomed to try out your proposed method!

One minor concern is that it may fit into the NLI objective which may not be the optimal solution for various tasks (e.g. STS, supervised ones). However, it has the potential to provide better results with reasonable amount of fine-tuning.

**Comment by hlang8160** [comment]
@BinWang28 
Ok, I will try it, Thanks.
