### ISSUE TITLE
Is `q` ever used?

### ISSUE THREAD

**Issue by JohnGiorgi** [BinWang28/SBERT-WK-Sentence-Embedding#9]
Hi, I am very interested in using this method with my own sentence encoder, so I have been going through the code/paper line-by-line to understand it. I noticed that this variable is computed but never used:

https://github.com/BinWang28/SBERT-WK-Sentence-Embedding/blob/ca65d43cbed637f2a7129669110782e9a6f7fe3b/utils.py#L118

Any reason to keep it around or is this just a typo?

**Comment by BinWang28** [comment]
Hi, John,

It is never been used. Feel free to remove it! :)
